<?php include 'auth.php'; ?>
<?php
// Autogenerated merge
?>
<!DOCTYPE html>
<html lang="id">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard Admin - YLBH</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      background-color: #f8f9fa;
    }

    .sidebar {
      height: 100vh;
      background-color: #800000;
      color: white;
      padding: 1rem;
    }

    .sidebar a {
      color: white;
      text-decoration: none;
      display: block;
      margin: 0.75rem 0;
    }

    .sidebar a:hover {
      text-decoration: underline;
    }

    .content {
      padding: 2rem;
    }

    .header {
      background-color: #fff;
      padding: 1rem 2rem;
      border-bottom: 1px solid #ddd;
    }
  </style>
</head>

<body>
  <div class="d-flex">
    <div class="sidebar">
      <h4>Admin YLBH</h4>
      <a href="#">Dashboard</a>
      <a href="pengacara-list.php">Kelola Pengacara</a>
      <a href="#">Kelola Layanan</a>
      <a href="#">Kelola Portofolio</a>
      <a href="#">Logout</a>
    </div>
    <div class="flex-grow-1">
      <div class="header">
        <h5>Selamat Datang, Admin</h5>
        <p class="text-muted">Panel kendali untuk mengelola konten website YLBH</p>
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-4">
            <div class="card shadow-sm">
              <div class="card-body">
                <h5 class="card-title">Total Pengacara</h5>
                <p class="card-text display-6">3</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card shadow-sm">
              <div class="card-body">
                <h5 class="card-title">Layanan Aktif</h5>
                <p class="card-text display-6">3</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card shadow-sm">
              <div class="card-body">
                <h5 class="card-title">Kasus Ditampilkan</h5>
                <p class="card-text display-6">5</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>