<?php
// Autogenerated merge
?>
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login / Register - YLBH</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
  <style>
    body {
      background: linear-gradient(to right, #800000, #a52a2a);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: 'Segoe UI', sans-serif;
      padding: 1rem;
    }

    .auth-card {
      width: 100%;
      max-width: 400px;
      background: #fff;
      border-radius: 12px;
      padding: 2rem;
      box-shadow: 0 8px 20px rgba(0,0,0,0.2);
    }

    .toggle-btn {
      background: none;
      border: none;
      color: #800000;
      cursor: pointer;
      font-weight: bold;
      padding: 0;
      text-decoration: underline;
    }

    .btn-primary {
      background-color: #800000;
      border: none;
    }

    .btn-primary:hover {
      background-color: #a52a2a;
    }

    .form-section {
      display: none;
      animation: fadeIn 0.3s ease-in-out;
    }

    .form-section.active {
      display: block;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: scale(0.98); }
      to { opacity: 1; transform: scale(1); }
    }
  </style>
</head>
<body>
  <div class="auth-card">
    <!-- Login Form -->
    <div class="form-section active" id="loginForm">
      <h4 class="text-center mb-4">Masuk</h4>
      <form action="login.php" method="POST">
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" name="username" class="form-control" required />
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" name="password" class="form-control" required />
        </div>
        <button class="btn btn-primary w-100 mb-3" type="submit">Login</button>
      </form>
      <p class="text-center">Belum punya akun?
        <button type="button" class="toggle-btn" onclick="toggleForm('register')">Daftar</button>
      </p>
    </div>

    <!-- Register Form -->
    <div class="form-section" id="registerForm">
      <h4 class="text-center mb-4">Buat Akun</h4>
      <form action="register.php" method="POST">
        <div class="mb-3">
          <label class="form-label">Nama Lengkap</label>
          <input type="text" name="fullname" class="form-control" required />
        </div>
        <div class="mb-3">
          <label class="form-label">Email</label>
          <input type="email" name="email" class="form-control" required />
        </div>
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" name="username" class="form-control" required />
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" name="password" class="form-control" required />
        </div>
        <button class="btn btn-primary w-100 mb-3" type="submit">Daftar</button>
      </form>
      <p class="text-center">Sudah punya akun?
        <button type="button" class="toggle-btn" onclick="toggleForm('login')">Login</button>
      </p>
    </div>
  </div>

  <script>
    function toggleForm(target) {
      document.getElementById('loginForm').classList.remove('active');
      document.getElementById('registerForm').classList.remove('active');
      if (target === 'register') {
        document.getElementById('registerForm').classList.add('active');
      } else {
        document.getElementById('loginForm').classList.add('active');
      }
    }
  </script>
</body>
</html>
